# Copyright (c) Meta Platforms, Inc. and affiliates.

name: Publish vpdq to pypi

on:
  push:
    branches:
      - main
    paths:
      - "vpdq/version.txt"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

defaults:
  run:
    working-directory: vpdq

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install packaging dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python vpdq-release.py -i
      - name: Package threatexchange
        run: |
          python vpdq-release.py -r
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: appleappleapplenanner
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: vpdq/dist
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          username: appleappleapplenanner
          password: ${{ secrets.pypi_password }}
          packages_dir: vpdq/dist
