# Copyright (c) Meta Platforms, Inc. and affiliates.

name: Publish vpdq to pypi

on:
  push:
    branches:
      - main
    paths:
      - "vpdq/version.txt"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: false
        type: string

defaults:
  run:
    working-directory: vpdq

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install packaging dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python vpdq-release.py -i
      - name: Package threatexchange
        run: |
          python vpdq-release.py -r
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: appleappleapplenanner
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: vpdq/dist
